// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnyuiozeezdhsdoefzmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueXVpb3plZXpkaHNkb2Vmem1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMzM5MjIsImV4cCI6MjA0OTcwOTkyMn0.fNvu_lRGOXJFSwm_wbX9T7aEgAeJWq3s5zl32nlu_4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);